# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
%{?!fdupes: %define fdupes echo}
# << macros

%{!?python_sitelib: %define python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}
Name:       obslight
Summary:    OBS Light
Version:    0.4.19
Release:    1
Group:      Development/Tools/Building
License:    GPLv2
BuildArch:  noarch
URL:        http://wiki.meego.com/OBS_Light
Source0:    %{name}-%{version}.tar.gz
Source100:  obslight.yaml
Requires:   mic >= 0.4
Requires:   sudo
Requires:   osc
Requires:   build
Requires:   qemu
Requires:   spectacle
Requires:   acl
Requires:   tightvnc
Requires:   tftp
%if 0%{?fedora}
Requires:   nfs-utils
%else
Requires:   nfs-kernel-server
Requires:   python-xml
%endif
Requires(post): /sbin/service
Requires(post): /sbin/chkconfig
Requires(postun): /sbin/service
Requires(postun): /sbin/chkconfig
BuildRequires:  python >= 2.6.0
BuildRequires:  python-devel >= 2.6.0
BuildRequires:  fdupes
BuildRequires:  xinetd
BuildRequires:  rpcbind
%if 0%{?fedora}
BuildRequires:   nfs-utils
%else
BuildRequires:  nfs-kernel-server
%endif
BuildRequires:  desktop-file-utils
BuildRoot:  %{_tmppath}/%{name}-%{version}-build


%description
Utilities to work with OBS Light, a lighter version of OBS.
This package contains the API, a commandline client,
and some tools (obstag, obs2obscopy, obsextractgroups).



%package gui
Summary:    Utilities to work with OBS Light - graphical interface
Group:      Development/Tools/Building
Requires:   %{name} = %{version}-%{release}
Requires:   obslight = %{version}
Requires:   python-pyside >= 1.0.6
Provides:   obslightgui

%description gui
Utilities to work with OBS Light, a lighter version of OBS.
This package contains the graphical interface.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

CFLAGS="$RPM_OPT_FLAGS" %{__python} setup.py build

# >> build post
# << build post
%install
rm -rf $RPM_BUILD_ROOT
# >> install pre
echo "%{version}-%{release}" > VERSION
# << install pre
%if 0%{?suse_version}
%{__python} setup.py install --root=$RPM_BUILD_ROOT --prefix=%{_prefix}
%else
%{__python} setup.py install --root=$RPM_BUILD_ROOT -O1
%endif

# >> install post
%fdupes -s $RPM_BUILD_ROOT/%{python_sitelib}
ln -s obslight-wrapper.py %{buildroot}/%{_bindir}/obslight
ln -s obslightgui-wrapper.py %{buildroot}/%{_bindir}/obslightgui

install -d $RPM_BUILD_ROOT/etc/init.d

install -m 744 ObsLightServer/obslightserver %{buildroot}%{_sysconfdir}/init.d/obslightserver

# << install post
desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop


%preun
# >> preun
echo "Trying to remove OBS Light server..."
%insserv_cleanup
%verify_permissions

echo "Trying to remove OBS Light sudoers rule..."
if [ $1 -eq "0" ]; then
if [ ! -f "%{_sysconfdir}/sudoers.tmp" ]; then
touch %{_sysconfdir}/sudoers.tmp
sed -i s/"#include .*sudoers\.obslight"// %{_sysconfdir}/sudoers
rm %{_sysconfdir}/sudoers.tmp
echo " DONE"
else
echo "Cannot modify sudoers file"
fi
else
echo " just updating, sudoers rule not modified"
fi
# << preun

%post
# >> post
echo "Trying to add OBS Light sudoers rule..."
if [ ! -f "%{_sysconfdir}/sudoers.tmp" ]; then
touch %{_sysconfdir}/sudoers.tmp
if [ -z "$(grep sudoers.obslight %{_sysconfdir}/sudoers)" ]; then
echo "#include %{_sysconfdir}/sudoers.obslight" >> %{_sysconfdir}/sudoers
echo " DONE"
else
echo " sudoers rule already configured"
fi
rm %{_sysconfdir}/sudoers.tmp
else
echo "Cannot modify sudoers file";
fi

echo "Trying to add OBS Light server..."
[ -d $RPM_BUILD_ROOT/srv/obslight ] || install -d -o nobody -g nobody $RPM_BUILD_ROOT/srv/obslight
echo "/srv/obslight  *(rw,fsid=0,no_root_squash,insecure,no_subtree_check)" >> /etc/exports

/sbin/insserv %{_sysconfdir}/init.d/xinetd
/sbin/insserv %{_sysconfdir}/init.d/rpcbind
/sbin/insserv %{_sysconfdir}/init.d/nfsserver
/sbin/insserv %{_sysconfdir}/init.d/obslightserver
# << post






%files
%defattr(-,root,root,-)
# >> files
%doc README VERSION
%{_bindir}/obs2obscopy
%{_bindir}/obstag
%{_bindir}/obsextractgroups
%{_bindir}/obslight
%{_bindir}/obslight-wrapper.py
%{python_sitelib}/ObsLight
%{python_sitelib}/obslight*egg-info
%config %attr(440, root, root) %{_sysconfdir}/sudoers.obslight
%config %{_sysconfdir}/bash_completion.d/obslight.sh
%config %{_sysconfdir}/xinetd.d/tftp
%config %attr(0755, root, root) %{_sysconfdir}/init.d/obslightserver
%dir %{_sysconfdir}/obslight
%config(noreplace) %attr(0644,root,root) %{_sysconfdir}/obslight/obslight.conf
%{_bindir}/ObsLightServer.py
# << files


%files gui
%defattr(-,root,root,-)
# >> files gui
%{_bindir}/obslightgui
%{_bindir}/obslightgui-wrapper.py
%{python_sitelib}/ObsLightGui
%{_datadir}/applications/obslightgui.desktop
%{_datadir}/pixmaps/obslight.png
# << files gui

