#!/bin/sh
ORIG=$PWD
API=$1
OBSPROJECT=$2
OUTDIR=$3
REPONAME=$4
SCHEDULERS="$5"

WGETOPTIONS="--no-check-certificate -N -c -r -nd -nH"

mkdir -p obs-repos/$OUTDIR/$REPONAME
cd obs-repos/$OUTDIR/$REPONAME
echo -e "\e[32;1mHave to dump :full for $SCHEDULERS\e[0m"
for scheduler in $SCHEDULERS; do
	echo -e "\e[32;1mDumping :full for scheduler '$scheduler'\e[0m"
	mkdir -p $scheduler
	cd $scheduler
	wget $WGETOPTIONS $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=cache
	wget $WGETOPTIONS $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=names
	wget $WGETOPTIONS $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=binaryversions
	wget $WGETOPTIONS $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=solvstate
	# Grab 
	python $ORIG/tools/printbinaries.py "_repository?view=names" \
		| xargs -L1 -Ixxx $ORIG/tools/curlunpack "$API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?xxx"
	cd ..
done
