#!/bin/bash

. /etc/rc.status

### BEGIN INIT INFO
# Provides:          hostnameMgr
# Start-Before:      obsstoragesetup
# Required-Start:    $network
# Required-Stop:     $null
# Default-Start:     3 5
# Default-Stop:      0 1 2 4 6
# Description:       Add the hostname to the /etc/hosts file after dhcp
### END INIT INFO



do_start () {
	if ! grep -q `hostname` /etc/hosts ; then echo "127.0.0.1    `hostname` localhost" >> /etc/hosts; fi
}
case "$1" in
	start)
  		do_start
 		;;
 	restart)
 		do_start
 		;;
	stop|eload|force-reload)
		echo "Error: argument '$1' not supported" >&2
		exit 3
		;;
	*)
		echo "Usage: $0 start|restart" >&2
		exit 3
		;;
esac 
rc_exit
