#!/bin/bash
#
# This script is executed whenever your appliance boots.  Here you can add
# commands to be executed before the system enters the first runlevel.  This
# could include loading kernel modules, starting daemons that aren't managed
# by init files, asking questions at the console, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

if [ -f /etc/init.d/suse_studio_firstboot ]
then

  # Put commands to be run on the first boot of your appliance here
  echo "Running SUSE Studio first boot script..."
  #echo appliance info 
  sed -i "/^exit 0/ i\. /var/config_ObsLight_boot_info" /etc/init.d/rc

  # Put obslightgui on desktop
  mkdir -p /etc/skel/Desktop
  cp /usr/share/applications/obslightgui.desktop /etc/skel/Desktop/
  mkdir -p /home/tux/Desktop
  cp /usr/share/applications/obslightgui.desktop /home/tux/Desktop/
  cp /usr/share/applications/YaST.desktop /home/tux/Desktop/
  chown -R tux:users /home/tux/Desktop
  chmod 744 /home/tux/Desktop/obslightgui.desktop
  chmod 744 /home/tux/Desktop/YaST.desktop
  # fix rights of tux's KDE configuration directory
  chown -R tux:users /home/tux/.kde4
  chmod -R a-rwx,u+rwX /home/tux/.kde4
fi

# remount / with ACLs
if [ -z "`mount | grep acl`" ]
then
  mount -o remount,acl /
fi

# use kwrite to open Kickstart files (recognized as java keystore files)
if [ -z `grep x-java-keystore /usr/share/applications/kde4/kwrite.desktop` ]
then
  sed -i s,"text/plain;","text/plain;application/x-java-keystore;", /usr/share/applications/kde4/kwrite.desktop
fi

# add consoleblank=0 option to the kernel command line
if [ -z "`grep consoleblank /boot/grub/menu.lst`" ]
then
  sed -i -r s/"(^[ \t]*kernel.*)"/"\1 consoleblank=0"/ /boot/grub/menu.lst
fi

#to disable GPG checks for OBS Light repo
if [ -f /etc/zypp/repos.d/Project_OBS_Light_openSUSE_12.1.repo ]
then
   sed -i -r s,"gpgcheck=1","gpgcheck=0", /etc/zypp/repos.d/Project_OBS_Light_openSUSE_12.1.repo
fi
