# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       mds-tools
Summary:    Mer Delivery System tools (fakeobs)
Version:    0.1
Release:    1
Group:      Development/Tools/Building
License:    GPLv2
BuildArch:  noarch
Source0:    %{name}-%{version}.tar.gz
Source100:  mds-tools.yaml
Requires:   git
Requires:   python
Requires:   python-async
Requires:   python-gitdb
Requires:   python-gitpython
Requires:   python-smmap
Requires(post): /sbin/service
Requires(post): /sbin/chkconfig
Requires(postun): /sbin/service
Requires(postun): /sbin/chkconfig


%description
Mer Delivery System tools, including fakeobs,
modified for the needs of OBS Light project




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/srv/fakeobs/obs-projects
mkdir -p %{buildroot}/srv/fakeobs/obs-repos
mkdir -p %{buildroot}/srv/fakeobs/packages-git
mkdir -p %{buildroot}/srv/fakeobs/releases
mkdir -p %{buildroot}%{_sysconfdir}/init.d
mkdir -p %{buildroot}%{_sbindir}
cp -rf tools %{buildroot}/srv/fakeobs/tools
cp -f init_fakeobs %{buildroot}%{_sysconfdir}/init.d/fakeobs
cp -f fakeobs %{buildroot}%{_sbindir}/
# << install pre

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%dir /srv/fakeobs
%dir /srv/fakeobs/*
/srv/fakeobs/tools/*
%config %{_sysconfdir}/init.d/fakeobs
%{_sbindir}/fakeobs
# << files


