# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       mds-tools
Summary:    Mer Delivery System tools (fakeobs)
Version:    0.1
Release:    1
Group:      Development/Tools/Building
License:    GPLv2
BuildArch:  noarch
URL:        https://meego.gitorious.org/meego-developer-tools/obs-light/trees/master
Source0:    %{name}-%{version}.tar.gz
Source100:  mds-tools.yaml
Requires:   git
Requires:   python
Requires:   python-async
Requires:   python-gitdb
Requires:   python-gitpython
Requires:   python-smmap
Requires(post): /sbin/service
Requires(post): /sbin/chkconfig
Requires(postun): /sbin/service
Requires(postun): /sbin/chkconfig


%description
Mer Delivery System tools, including fakeobs,
modified for the needs of OBS Light project




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/srv/fakeobs/obs-projects
mkdir -p %{buildroot}/srv/fakeobs/obs-repos
mkdir -p %{buildroot}/srv/fakeobs/packages-git
mkdir -p %{buildroot}/srv/fakeobs/releases
mkdir -p %{buildroot}%{_sysconfdir}/init.d
mkdir -p %{buildroot}%{_sbindir}
cp -rf tools %{buildroot}/srv/fakeobs/tools
cp -f init_fakeobs %{buildroot}%{_sysconfdir}/init.d/fakeobs

ln -sf /srv/fakeobs/tools/fakeobs.py %{buildroot}%{_sbindir}/fakeobs
ln -sf %{_sysconfdir}/init.d/fakeobs %{buildroot}%{_sbindir}/rcfakeobs

# << install pre

# >> install post
mkdir -p %{buildroot}%{_sysconfdir}/apache2/vhosts.d
mkdir -p %{buildroot}%{_sysconfdir}/lighttpd/vhosts.d
cp -f fakeobs-repos.apache2conf %{buildroot}%{_sysconfdir}/apache2/vhosts.d/fakeobs-repos.conf
cp -f fakeobs-repos.lighttpdconf %{buildroot}%{_sysconfdir}/lighttpd/vhosts.d/fakeobs-repos.conf
# << install post


%preun
# >> preun
%stop_on_removal fakeobs
# << preun

%post
# >> post
cd /srv/fakeobs/
if [ ! -f lastevents ]
then
touch lastevents
sh tools/addevent initial na na
fi

if [ ! -f mappings.xml ]
then
echo -e "<mappings>\n</mappings>" > mappings.xml
fi
# << post

%postun
# >> postun
%restart_on_update fakeobs
%insserv_cleanup
# << postun


%files
%defattr(-,root,root,-)
# >> files
%dir /srv/fakeobs
%dir /srv/fakeobs/obs-projects
%dir /srv/fakeobs/obs-repos
%dir /srv/fakeobs/packages-git
%dir /srv/fakeobs/releases
%dir /srv/fakeobs/tools
/srv/fakeobs/tools/*
%config %{_sysconfdir}/init.d/fakeobs
%config %{_sysconfdir}/apache2/vhosts.d/fakeobs-repos.conf
%config %{_sysconfdir}/lighttpd/vhosts.d/fakeobs-repos.conf
%{_sbindir}/fakeobs
%{_sbindir}/rcfakeobs
# << files


