#!/bin/bash
# Authors Ronan Le Martret (Intel OTC)
# ronan@fridu.net
# Date 03 january 2012
# License GLPv2

if [ ! -f /etc/sysconfig/boss-skynet ]; then  
cat >> /etc/sysconfig/boss-skynet <<EOF
# Sourced by skynet scripts

SERVICE_DIR=/var/lib/SkyNET/services/
STORAGE_DIR=/var/lib/SkyNET/store/
EOF
fi

chmod 0640 /etc/sudoers
cat >> /etc/sudoers << EOF
nobody ALL=(ALL)NOPASSWD:/usr/bin/mic-image-creator
EOF
chmod 0440 /etc/sudoers

install -d -m 0777 /var/www/img/images
install -d -m 0777 /var/www/img/templates 

patch /usr/lib/python/site-packages/img_web/templates/registration/login.html << EOF
8a9
> <p>(by default Username:imager Password:imager)</p>
EOF

cat > /etc/lighttpd/vhosts.d/img.conf << EOF
var.namebasedir = "/img"
  
\$HTTP["url"] =~ "^" + namebasedir {
       dir-listing.activate = "enable"
}

url.redirect += (
 "^" + namebasedir + "$" => namebasedir + "/"
)

fastcgi.server += (
   "/img.fcgi" => (
       "main" => (
           "socket" => "/var/run/img_web" + ".socket",
           "check-local" => "disable",
           "allow-x-send-file" => "enable",
       )
   ),
)

url.rewrite-if-not-file += (
   "^(" + namebasedir + "/.*)$" => "/img.fcgi/\$1"
)
EOF
echo 'include "/etc/lighttpd/vhosts.d/img.conf"' >> /etc/lighttpd/lighttpd.conf

patch /etc/lighttpd/modules.conf << EOF
41c41
< 
---
> global{
44,50c44,48
< #  "mod_alias",
< #  "mod_auth",
< #  "mod_evasive",
< #  "mod_redirect",
< #  "mod_rewrite",
< #  "mod_setenv",
< #  "mod_usertrack",
---
>   "mod_alias",
>   "mod_accesslog",
>   "mod_compress",
>   "mod_fastcgi",
>   "mod_rewrite",
51a50
> }
EOF

rm -r /var/lib/rabbitmq/mnesia/*











