#!/bin/bash
#
# This script is executed whenever your appliance boots.  Here you can add
# commands to be executed before the system enters the first runlevel.  This
# could include loading kernel modules, starting daemons that aren't managed
# by init files, asking questions at the console, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

if [ -f /etc/init.d/suse_studio_firstboot ]
then

  # Put commands to be run on the first boot of your appliance here
  echo "Running SUSE Studio first boot script..."
  sed -i "/^exit 0/ i\echo Start ..." /etc/init.d/rc
  sed -i "/^exit 0/ i\[ ! -f /var/imagerinstall ] && . /var/config_host_install | tee /var/log/imagerinst.log" /etc/init.d/rc
  #echo appliance info 
  sed -i "/^exit 0/ i\. /var/config_Imager_boot_info" /etc/init.d/rc
fi



