#!/bin/bash
#
# This script is executed whenever your appliance boots.  Here you can add
# commands to be executed before the system enters the first runlevel.  This
# could include loading kernel modules, starting daemons that aren't managed
# by init files, asking questions at the console, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile
echo "http://wiki.meego.com/Release_Infrastructure/IMG_Installation_using_Suse_Studio"
echo "Root password: opensuse" 
echo Server OBS ready http://`/sbin/ifconfig  | grep 'inet '| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`/
if [ -f /etc/init.d/suse_studio_firstboot ]
then

  # Put commands to be run on the first boot of your appliance here
  echo "Running SUSE Studio first boot script..."
  sed -i "/^exit 0/ i\echo Start ..." /etc/init.d/rc
  sed -i "/^exit 0/ i\[ ! -f /var/imagerinstall ] && . /var/config_host_install | tee /var/log/imagerinst.log" /etc/init.d/rc
  
fi
