#!/bin/sh

if [ ! -f "/etc/sudoers.tmp" ]; then
  touch /etc/sudoers.tmp
  sed -i s/"#include .*sudoers\.obslight"// /etc/sudoers
  rm /etc/sudoers.tmp
fi

if [ -d /etc/apache2/sites-available ]
then
  a2dissite obslight-image.conf
  a2dissite obslight-repos.conf
  unlink /etc/apache2/sites-available/obslight-image.conf
  unlink /etc/apache2/sites-available/obslight-repos.conf
  service apache2 reload
fi

xdg-desktop-menu uninstall /usr/share/applications/obslightgui.desktop

