#!/bin/bash
#
# This script is executed whenever your appliance boots.  Here you can add
# commands to be executed before the system enters the first runlevel.  This
# could include loading kernel modules, starting daemons that aren't managed
# by init files, asking questions at the console, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

#add the hostname to the hosts file (before run level 3)

if [ -f /etc/init.d/suse_studio_firstboot ]
then

  # Put commands to be run on the first boot of your appliance here
  echo "Running SUSE Studio first boot script..."

  rcmysql start
  rcobsapisetup start
  rcobsstoragesetup start

  # fix hostname in testdrive: 
  sed -i 's,^webui_host: .*,webui_host: "'"127.0.0.1"'",' /srv/www/obs/api/config/options.yml

  #insserv lighttpd
  #rclighttpd restart
  #echo appliance info 
  sed -i "/^exit 0/ i\. /var/config_obs_boot_info" /etc/init.d/rc
  obslight-fakeobs createlink
fi

#to disable GPG checks for OBS Light repo
if [ -f /etc/zypp/repos.d/OBS_Light.repo ]
then
   sed -i -r s,"gpgcheck=1","gpgcheck=0", /etc/zypp/repos.d/OBS_Light.repo
fi

# Refrech DOD primary.xml
obsdodupdate https://localhost:444 MeeGo_DOD:1.2:oss standard i586
obsdodupdate https://localhost:444 MeeGo_DOD:1.2.0:oss standard i586
